#!/usr/bin/env python3
import argparse
import re
from pathlib import Path


HEADING_RE = re.compile(r"^## \[(?P<tag>[^\]]+)\](?:\s+-\s+(?P<date>.*))?$")
SUBHEADING_RE = re.compile(r"^###\s+(?P<title>.+)$")
PRERELEASE_RE = re.compile(r"^(?P<base>.+?)-(?:alpha|beta|rc)\d*$", re.IGNORECASE)
SEMVER_RE = re.compile(r"^(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)$")
HEADING_ICON_PREFIX_RE = re.compile(r"^[^\w\[\(]+", re.UNICODE)


def lua_string(value):
    value = value or ""
    value = value.replace("\\", "\\\\").replace('"', '\\"')
    value = value.replace("\r", "\\r").replace("\n", "\\n")
    return f'"{value}"'


def strip_gate_markers(lines):
    out = []
    for line in lines:
        text = line.strip()
        if text in ("<!--@eqol-beta@-->", "<!--@end-eqol-beta@-->"):
            continue
        if text.startswith("#@") or text.startswith("<!--@"):
            continue
        out.append(line)
    return out


def clean_section_title(title):
    title = (title or "").strip().replace("\ufe0f", "")
    for marker in ("✨", "🐛", "ℹ", "❌"):
        title = title.replace(marker, "")
    title = HEADING_ICON_PREFIX_RE.sub("", title).strip()
    return title


def parse_changelog(changelog):
    lines = strip_gate_markers(changelog.splitlines())
    releases = []
    current_release = None
    current_section = None

    def flush_section():
        nonlocal current_section
        if current_release is not None and current_section is not None and current_section["items"]:
            current_release["sections"].append(current_section)
        current_section = None

    def flush_release():
        nonlocal current_release
        flush_section()
        if current_release is not None and current_release["sections"]:
            releases.append(current_release)
        current_release = None

    for raw in lines:
        line = raw.strip()
        heading = HEADING_RE.match(line)
        if heading:
            flush_release()
            current_release = {
                "tag": heading.group("tag"),
                "date": heading.group("date") or "",
                "sections": [],
            }
            continue

        if current_release is None:
            continue

        subheading = SUBHEADING_RE.match(line)
        if subheading:
            flush_section()
            current_section = {
                "title": clean_section_title(subheading.group("title")),
                "items": [],
            }
            continue

        if not line or line == "---":
            continue

        if line.startswith("- "):
            if current_section is None:
                current_section = {"title": "", "items": []}
            current_section["items"].append(line[2:].strip())

    flush_release()
    return releases


def prerelease_base(tag):
    match = PRERELEASE_RE.match(tag or "")
    return match.group("base") if match else None


def patch_family(tag):
    match = SEMVER_RE.match(tag or "")
    if not match:
        return None

    patch = int(match.group("patch"))
    if patch <= 0:
        return None

    return f"{match.group('major')}.{match.group('minor')}"


def release_in_patch_family(release_tag, family):
    match = SEMVER_RE.match(release_tag or "")
    if not match:
        return False

    return f"{match.group('major')}.{match.group('minor')}" == family


def select_releases(releases, tag):
    if not releases:
        return []

    selected_tag = tag or releases[0]["tag"]
    index = next((i for i, release in enumerate(releases) if release["tag"] == selected_tag), None)
    if index is None:
        index = 0
        selected_tag = releases[0]["tag"]

    base = prerelease_base(selected_tag)
    if base:
        selected = []
        include_family = patch_family(base)
        for release in releases:
            if prerelease_base(release["tag"]) == base:
                selected.append(release)
            elif selected and include_family and release_in_patch_family(release["tag"], include_family):
                selected.append(release)
            elif selected:
                break
        return selected or [releases[index]]

    family = patch_family(selected_tag)
    if family:
        selected = []
        for release in releases[index:]:
            if release_in_patch_family(release["tag"], family):
                selected.append(release)
            else:
                break
        return selected or [releases[index]]

    return [releases[index]]


def build_lua(releases, source_tag):
    lines = [
        "-- This file is generated by scripts/generate_changelog_lua.py. Do not edit manually.",
        "local _, addon = ...",
        "",
        "addon.GeneratedChangelog = {",
        f"\tsourceTag = {lua_string(source_tag or '')},",
        "\treleases = {",
    ]
    for release in releases:
        lines.extend(
            [
                "\t\t{",
                f"\t\t\ttag = {lua_string(release['tag'])},",
                f"\t\t\tdate = {lua_string(release['date'])},",
                "\t\t\tsections = {",
            ]
        )
        for section in release["sections"]:
            lines.extend(
                [
                    "\t\t\t\t{",
                    f"\t\t\t\t\ttitle = {lua_string(section['title'])},",
                    "\t\t\t\t\titems = {",
                ]
            )
            for item in section["items"]:
                lines.append(f"\t\t\t\t\t\t{lua_string(item)},")
            lines.extend(["\t\t\t\t\t},", "\t\t\t\t},"])
        lines.extend(["\t\t\t},", "\t\t},"])
    lines.extend(["\t},", "}", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate an ingame Lua changelog from CHANGELOG.md.")
    parser.add_argument(
        "tag",
        nargs="?",
        default="",
        help="Release tag to select. Patch releases include earlier entries from the same major/minor series.",
    )
    parser.add_argument("--changelog", default="CHANGELOG.md")
    parser.add_argument("--output", default="EnhanceQoL/GeneratedChangelog.lua")
    args = parser.parse_args()

    changelog = Path(args.changelog).read_text(encoding="utf-8")
    releases = parse_changelog(changelog)
    selected = select_releases(releases, args.tag)
    Path(args.output).write_text(build_lua(selected, args.tag), encoding="utf-8")
    included = ", ".join(release["tag"] for release in selected) or "none"
    print(f"Generated {args.output}; included sections: {included}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
